LABEL name="neovim" \
      summary="Neovim contained (based on fedora)" \
      maintainer="Sandorex <rzhw3h@gmail.com>"

ARG VERSION=39
FROM fedora:$VERSION
ARG VERSION

# improve DNF experience
RUN echo "max_parallel_downloads=10" >> /etc/dnf/dnf.conf \
    && echo "defaultyes=True" >> /etc/dnf/dnf.conf \
    && echo "fastestmirror=True" >> /etc/dnf/dnf.conf \
    && echo "install_weak_deps=False" >> /etc/dnf/dnf.conf

# install rpmfusion
RUN dnf -y install "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-${VERSION}.noarch.rpm" \
   && dnf -y install "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-${VERSION}.noarch.rpm"

# packages in outside script as they are long and easier to edit in script form
COPY ./install_packages.sh /
RUN /install_packages.sh \
    && rm -rf /install_packages.sh \
    && dnf clean all

# set locale
ENV LC_ALL=en_US.UTF-8

ENV ws=/ws
WORKDIR ${ws}

# by default print the wrapper script so it could be installed easily
COPY ./nvim-wrapper /
ENTRYPOINT [ "cat", "/nvim-wrapper" ]

